service:
  name: serverless-signed-urls

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.handler
    events:
      - http:
          method: get
          path: hello
